name: CI

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  nodejs:
    name: Node.js
    runs-on: ubuntu-latest
    concurrency: ci-nodejs-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Packages
        run: pnpm install

      - name: Typecheck server
        run: pnpm run typecheck
        working-directory: ./server

      - name: Build Server
        run: pnpm run build
        working-directory: ./server

      - name: Typecheck client
        run: pnpm run typecheck
        working-directory: ./client

      - name: Restore Atlas Cache
        id: cache-atlases-restore
        uses: actions/cache@v4
        with:
          path: ./client/node_modules/.atlas-cache/
          key: atlas-cache

      - name: Build Client
        run: pnpm run build
        working-directory: ./client

      - name: Save Atlas Cache
        id: cache-atlases-save
        uses: actions/cache/save@v4
        with:
          path: ./client/node_modules/.atlas-cache/
          key: atlas-cache
  lint:
    name: Lint
    runs-on: ubuntu-latest
    concurrency: ci-lint-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run Biome
        run: biome ci .

  tests:
    name: Tests
    runs-on: ubuntu-latest
    concurrency: ci-lint-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Packages
        run: pnpm install

      - name: Run tests
        run: pnpm run test
        working-directory: ./tests
