name: Client

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths: &paths
      - "client/**"
      - "shared/**"
      - "*.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/client.yml"

  pull_request:
    paths: *paths

jobs:
  client:
    name: Client
    runs-on: ubuntu-latest
    concurrency: ci-nodejs-${{ github.ref }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Packages
        run: pnpm install --filter client --filter shared

      - name: Typecheck client
        run: pnpm run typecheck
        working-directory: ./client

      - name: Restore Atlas Cache
        id: cache-atlases-restore
        uses: actions/cache@v4
        if: always()
        with:
          path: ./client/node_modules/.atlas-cache/
          key: "atlas-cache-${{ github.run_id }}"
          restore-keys: |
            atlas-cache

      - name: Build Client
        run: pnpm run build
        working-directory: ./client
        if: always()
      - name: Save Atlas Cache
        id: cache-atlases-save
        uses: actions/cache/save@v4
        with:
          path: ./client/node_modules/.atlas-cache/
          key: "atlas-cache-${{ github.run_id }}"
